sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: Jv5Ic6F5AI7l8zgSrQqeX1bSr2xPoqLuSGTMA8SX/i3/gi86MQOMPP31imuy0+Ruktumsf9IDIR1SqpoafVfF6LJegrA5RHZ1w/j6SAAqy1s1DeMIbrhZuitF5EAYjSYW14lL5mGuQS80vLFr8lgaJJpxcrpgiVig79QRfspZOG0gdyAgLb4Av6tkYpSmW2lnLIh0awHuGoQi1jHe0x+vqnGCpH/WqJ/NhVTKWX2WHZHFreLTXOyAs1gDQ7l1BG9EEtCGM67QFL/Yfz+BDa5QTsBkMiVXVn08fkMkScVDMVdaXE2sLieqgmWh40s52cb6oGEN2u0Eg2PD3cTorWu/6Lf2jyPMYhq0XCwa81MYoGRAzXAghn8bqjyslSynCvXFe3skm3gCx09kZQ+I3GNP/Op5whkGj8F9o4asoLZMNNOuLvzvBAnvBc8S3N3t8DdcLzHhCuNx+HqD/AmerxVndPnWuggLwyrD0WqX84lCTiT/M3wTgqSosYm7Exa2UDexktg/yktP2GpVfBXQFnMu7rJt0CmGP6sVGhXcRx5z56/ZOFYNgl0Z8RrasWPOl9Gqj0u6bTLzsTTh7utHLg77Cdp25muGaiOaN3Rebawin82x5QxxsQVEknTzMroXR1i/cMhVilN83Oau8FfylSY+EpgYEPEjq8wkgyacfL/gMc=}, {secure: dvVb4rLf+ov6kqlBpXDvaJQQC9FT0rF/MF6ZZ5u61oGrHZZgEicgyZzzauLdr6+JaffUDTNfK6brA68cpGMso9ynZR0aSMqH6Akpuq+RyUNJz3lrvNcNEOfICHENX21Ovhysv5injteUR7mKxJ3kQIShmrc5AXhH+UnFnus05yHpUVY1UYCJ4ku1uTi/6o6GR4l0beCFdu6YHkw1TJ/qmDVVLuI7xn4VyKdn6bH9qhgf2XcZJRxatrcZA+4cqVqlmXb7SWeRXx3bqmTs7IeY1Kih8ArYD8xjOE0emwL2ocY+z3MIXb3xnEr7lH0E7y0fBt05F3X7S3/KJyUgbLdsxKPyVVmQvum0/pd1Q/2jpa3bjLMondhzdU7NfaHx83G8zRcs3YqbRgfOFxSg3T+iwF+UYiM2Axsj+nZtWT5oNNs0GTRB8m0kDwydMKdDMAnRoaM+jCA8LSjE4CssaO3hDJTIa+AqJP9Imhgy1uVuiIY6fCZGfAyvU2JKLTH4V+EDsz4Fj5dM5+0fZY6yqN6n8SwMgL015vydCML6EsXX0RJ7TCCMNAdnUH3zZHOTWQ4QbmHrENv5o8LtehqcNa0mjpdILKxcTJvFSIcYbBVqqXpxaH4+1MXxwfOGSmHCJLKIaB+DzysG0dlNtchrNyuopLio6/wSR0Hh+dkT8+UmajI=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
